### ISSUE TITLE
Fix TypeStat conversion in metastore.py

### ISSUE THREAD

**Issue by criccomini** [recap-build/pymetastore#27]
I noticed several of the TypeStats constructed in `get_table_stats` have incorrect params. Several have `cardinality` in their constructor, but aren't getting that supplied. Others are being passed numDVs when they don't have that.

**Comment by criccomini** [comment]
According to this, no `cardinality` param exists:

https://devdoc.net/bigdata/hive-confluence-20210220/display/Hive/Column+Statistics+in+Hive.html

**Comment by cpard** [comment]
> According to this, no `cardinality` param exists:
> 
> https://devdoc.net/bigdata/hive-confluence-20210220/display/Hive/Column+Statistics+in+Hive.html

yes, HMS is using DV (distinct values) instead of cardinality, I used cardinality as I find it more descriptive than using DV. I'll take a look to see what inconsistencies are there and fix them.

**Comment by cpard** [comment]
@criccomini check #28

**Comment by criccomini** [comment]
Closed by https://github.com/recap-build/pymetastore/pull/28
